apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pv-claim
  namespace: myapp-ns
spec:
  storageClassName: hostpath
  selector:
    matchExpressions:
      - { key: intent, operator: In, values: [logs] }
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
