// https://www.jenkins.io/doc/book/pipeline/syntax/
// Build a Build Jenkins image using dockerfile and using it to build an app
pipeline{
	agent { dockerfile true }

	stages {
        stage ('Docker build') {
            steps {
				    sh 'docker build -t myapp ./question1_folder'
                  }
			}

        stage ('Deploy Kubernates stateful and persistence claims') {
           steps {
               script{
                    sh  '''
                            kubectl create -f ./question2_folder/namespace.yaml
                            kubectl create -f ./question2_folder/nginx-config.yaml
                            kubectl create -f ./question2_folder/persistance-volume.yaml
                            kubectl create -f ./question2_folder/persistance-volume-claim.yaml
                            kubectl create -f ./question2_folder/secret.yaml
                            kubectl create -f ./question2_folder/kubernetes-stateful.yaml
                            kubectl create -f ./question2_folder/headless-hostmachine-service.yaml
                        '''          
                    }
            }
        }
        post('Build successful')  {
            success  { }
            failure  {  ...  }

        }
    }
}